file:
    upload-dir: /Code/UdemySpringBoot/UploadDir
flyway:
    schemas: react_with_spring_boot
    url: jdbc:mysql://localhost:3308/
    user: root
    password: admin
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/react_with_spring_boot?useTimezone=true&serverTimezone=UTC
        username: root
        password: admin
    jackson:
        default-property-inclusion: NON_NULL
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: false
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
